/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/aging/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aging curves by position
         * @description A player's attacking output at each age as a multiple of his own output at 25 (within-player estimate, league-adjusted, 95% bootstrap band). Descriptive: the backtest found the curves add no forecasting value beyond regression to the mean.
         */
        get: operations["v1_aging_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness (does not load the models) */
        get: operations["v1_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * League-strength factors
         * @description Estimated from players who changed league: a factor of 0.85 means the same player typically produces ~15% less attacking output per 90 there than the five-league average (difficulty mixed with playing style).
         */
        get: operations["v1_leagues_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data and model coverage */
        get: operations["v1_meta_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player profile
         * @description Bio from Transfermarkt (when linked) and every season with per-90 rates and percentiles.
         */
        get: operations["v1_players_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/comps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comparable players
         * @description The player-seasons most similar to this one, controlled for position, age (+-1.5 years) and league quality, one row per distinct player, with what each went on to become and a gap analysis against the comp set. Similarity is by statistical profile; the backtest found it adds no predictive power beyond current level, so use it as evidence, not as the probability.
         */
        get: operations["v1_players_comps_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/forecast/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trajectory forecast
         * @description Probabilities for what the player becomes over the next `horizon` seasons, with a model-uncertainty range, a market-value range, and the comps as evidence. The headline comes from a learned model (validated in a rolling-origin backtest); `comps_alone` shows the weaker comps-only estimate.
         */
        get: operations["v1_players_forecast_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/outlook/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fan-chart outlook
         * @description Where the player's level (composite percentile, 0-100) is likely to be 1, 2 and 3 seasons from the chosen season, as a 10/50/90% band, plus the probability he is still a regular top-5-league player at each point. Forwards, wingers and midfielders with 900+ minutes in the season.
         */
        get: operations["v1_players_outlook_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/value/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price versus output
         * @description For forwards, wingers and midfielders: how far each season's market value sat below or above what peers with the same output and age are valued at. Backtested: players priced lowest for their output gained roughly 19% more value over the next season than the highest-priced (33% over two), counting players who left the five leagues. It is about Transfermarkt's value estimate, not transfer fees.
         */
        get: operations["v1_players_value_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search players by name
         * @description Accent-insensitive; every query word must appear in the name. Exact and prefix matches rank first, then by career minutes. Intended for autocomplete.
         */
        get: operations["v1_players_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Team style profile and gaps
         * @description Ten tactical-style dimensions ranked against the league that season (higher = better), from Understat team data. A gap is a dimension in the bottom quartile (threshold adjustable). Pressing and penetration are stable year to year; transition and set-piece threat are noisy and flagged as such.
         */
        get: operations["v1_teams_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search teams by name */
        get: operations["v1_teams_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/shortlist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidate players for a team gap (heuristic)
         * @description Ranks players in suitable positions by their percentile on the metrics that plausibly bear on the gap, capped by default at the market value of the club's most valuable player, with price-versus-output and where the age sits on the position's output plateau. A labelled heuristic: an observational test found that signings explain only a few points of R-squared of next season's style change, so it does not predict that a signing closes the gap. Set-piece defending has no mapping.
         */
        get: operations["v1_teams_shortlist_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgingGroup: {
            position_group: string;
            label: string;
            /** @description Ages within 3% of the estimated maximum (smoothed) */
            plateau_from: number;
            plateau_to: number;
            points: components["schemas"]["AgingPoint"][];
        };
        AgingPoint: {
            age: number;
            /** Format: double */
            multiple_of_25: number;
            /** Format: double */
            lo: number | null;
            /** Format: double */
            hi: number | null;
            n_obs: number;
        };
        AgingResponse: {
            groups: components["schemas"]["AgingGroup"][];
            notes: string[];
        };
        Candidate: {
            player_id: number;
            name: string;
            team: string | null;
            league: string;
            position_group: string;
            /** Format: double */
            age: number;
            age_note: string;
            /** Format: double */
            minutes: number;
            /**
             * Format: double
             * @description Mean percentile within position on the metrics that bear on the gap
             */
            fit: number;
            /** Format: double */
            market_value_eur: number | null;
            /** Format: double */
            price_vs_output_pct: number | null;
        };
        Comp: {
            player_id: number;
            name: string;
            season: number;
            league: string;
            team: string | null;
            /** Format: double */
            age: number;
            /** Format: double */
            minutes: number;
            /**
             * Format: double
             * @description Smaller = more similar (not comparable across different targets)
             */
            distance: number;
            /** @description What this comp became over the next horizon seasons: elite, good, regular, out (or retained/out for defenders and goalkeepers). Null when that window is not finished yet. */
            outcome: string | null;
            /**
             * Format: double
             * @description Peak market value over the horizon / value at the time
             */
            value_ratio: number | null;
            per90: {
                [key: string]: number | null;
            };
        };
        CompsResponse: {
            target: components["schemas"]["Target"];
            /** @description Stats the comparison used; seasons before 2016 lack FBref defensive stats */
            features_used: string[];
            horizon: number;
            comps: components["schemas"]["Comp"][];
            gap_analysis: components["schemas"]["Gap"][];
        };
        ForecastResponse: {
            player: components["schemas"]["Target"];
            /** @description Seasons ahead */
            horizon: number;
            /** @description Latest season of information used */
            as_of: number;
            /** @description True when the outcome window is already complete, so this is not a true forecast */
            retrospective: boolean;
            /** @description 'learned model' or 'comps + base rate' (defenders and goalkeepers) */
            headline_source: string;
            range_kind: string;
            calibrated: boolean;
            probabilities: components["schemas"]["OutcomeProbability"][];
            value: components["schemas"]["ValueProjection"] | null;
            evidence_comps: components["schemas"]["Comp"][];
            n_comps_used: number;
            caveats: string[];
        };
        Gap: {
            metric: string;
            label: string;
            /** Format: double */
            target_pct: number;
            /** Format: double */
            comp_median_pct: number;
            /** Format: double */
            comp_p25: number;
            /** Format: double */
            comp_p75: number;
            /**
             * Format: double
             * @description Target percentile minus comp median, in percentile points
             */
            gap: number;
            /** @description 'weakness' or 'strength' beyond +-15 points, else empty */
            flag: string;
            n_comps: number;
        };
        Health: {
            status: string;
            models_loaded: boolean;
        };
        LeagueStrength: {
            league: string;
            /** Format: double */
            factor: number;
            /** Format: double */
            ci_low: number | null;
            /** Format: double */
            ci_high: number | null;
            n_obs: number;
            n_movers: number;
        };
        LevelPoint: {
            season: number;
            /**
             * Format: double
             * @description Position-specific composite percentile, 0-100
             */
            level: number;
        };
        Meta: {
            players: number;
            player_seasons: number;
            seasons: number[];
            leagues: string[];
            horizon: number;
            as_of: number;
            calibrated: boolean;
            forecast_bootstrap_fits: number;
            /** @description Path of the backtest report in the repository */
            backtest_report: string;
        };
        OutcomeProbability: {
            outcome: string;
            label: string;
            /** Format: double */
            probability: number;
            /** Format: double */
            p10: number | null;
            /** Format: double */
            p90: number | null;
            /**
             * Format: double
             * @description The same outcome read straight off the comps (backtested as the weaker estimate)
             */
            comps_alone: number;
            /**
             * Format: double
             * @description Share of players of that position and age who ended up here
             */
            base_rate: number;
        };
        OutlookHorizon: {
            /** @description Seasons ahead */
            horizon: number;
            /** @description Start year of the season forecast */
            season: number;
            /** Format: double */
            p10: number;
            /** Format: double */
            p50: number;
            /** Format: double */
            p90: number;
            /**
             * Format: double
             * @description Probability he is still a 900+ minute top-5-league player then; the band is conditional on it
             */
            p_observed: number;
        };
        OutlookResponse: {
            player: components["schemas"]["Target"];
            /** @description False for defenders and goalkeepers (no composite level) and players below 900 minutes */
            covered: boolean;
            /** Format: double */
            level_now: number | null;
            history: components["schemas"]["LevelPoint"][];
            horizons: components["schemas"]["OutlookHorizon"][];
            model: string;
            notes: string[];
        };
        PlayerProfile: {
            player_id: number;
            name: string;
            position_group: string | null;
            /** @description Linked Transfermarkt id, when the link exists */
            tm_player_id: number | null;
            birth_date: string | null;
            nationalities: string[];
            height_cm: number | null;
            foot: string | null;
            tm_position: string | null;
            /** @description Latest season usable for comps/forecast (450+ minutes, age known) */
            latest_season: number | null;
            seasons: components["schemas"]["SeasonStats"][];
        };
        PlayerSearchResult: {
            /** @description Understat player id (the id used by every other endpoint) */
            player_id: number;
            name: string;
            /** @description Start year of the most recent season, e.g. 2024 = 2024/25 */
            latest_season: number;
            team: string | null;
            league: string;
            /** @description GK, DEF, MID, WING_AM or FWD */
            position_group: string | null;
            /**
             * Format: double
             * @description Age in that season (decimal years, mid-season)
             */
            age: number | null;
            /** Format: double */
            minutes: number;
        };
        PlayerValue: {
            player_id: number;
            name: string;
            position_group: string | null;
            /** @description False for defenders and goalkeepers, which the lens does not cover */
            covered: boolean;
            seasons: components["schemas"]["PricePoint"][];
            reading: string;
        };
        PricePoint: {
            season: number;
            team: string | null;
            /** Format: double */
            market_value_eur: number | null;
            /**
             * Format: double
             * @description % by which his value sits below (negative) or above (positive) that of peers with the same output and age; null for seasons the lens does not cover
             */
            price_vs_output_pct: number | null;
            standing: string | null;
        };
        SeasonStats: {
            season: number;
            league: string;
            team: string | null;
            position_group: string | null;
            /** Format: double */
            age: number | null;
            /** Format: double */
            minutes: number;
            games: number | null;
            /**
             * Format: double
             * @description Transfermarkt squad value at the end of that season
             */
            market_value_eur: number | null;
            /** @description Per-90 rates; *_adj are league-adjusted */
            per90: {
                [key: string]: number | null;
            };
            /** @description 0-100 within position group and season. *_pct_global ranks across leagues on league-adjusted rates; *_pct_league ranks within the league. Empty below 450 minutes. */
            percentiles: {
                [key: string]: number | null;
            };
        };
        ShortlistResponse: {
            team: string;
            season: number;
            gap: components["schemas"]["TeamDimension"];
            /** @description False when no player metric can address this gap with the free data */
            mapped: boolean;
            note: string;
            /** Format: double */
            ceiling_eur: number | null;
            candidates: components["schemas"]["Candidate"][];
            method: string;
        };
        Target: {
            player_id: number;
            name: string;
            season: number;
            league: string;
            team: string | null;
            position_group: string;
            /** Format: double */
            age: number;
            /** Format: double */
            minutes: number;
        };
        TeamDimension: {
            dimension: string;
            label: string;
            /**
             * Format: double
             * @description Among the league's teams that season; higher is better
             */
            percentile: number;
            /**
             * Format: double
             * @description Raw per-match value (PPDA for pressing)
             */
            value: number | null;
            is_gap: boolean;
            /** @description Low season-to-season persistence: a gap here may be partly noise */
            noisy: boolean;
        };
        TeamProfile: {
            team: string;
            league: string;
            season: number;
            /** Format: double */
            points_per_match: number;
            /** Format: double */
            xpts_per_match: number;
            /** Format: double */
            xg_per_match: number;
            /** Format: double */
            xga_per_match: number;
            dimensions: components["schemas"]["TeamDimension"][];
        };
        TeamSearchResult: {
            team: string;
            league: string;
            latest_season: number;
        };
        ValueProjection: {
            /** Format: double */
            now_eur: number;
            /** Format: double */
            p10_eur: number;
            /** Format: double */
            p50_eur: number;
            /** Format: double */
            p90_eur: number;
            /**
             * Format: double
             * @description Highest value in the data; projections are capped here
             */
            ceiling_eur: number | null;
            conditional_on: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_aging_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgingResponse"];
                };
            };
        };
    };
    v1_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    v1_leagues_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueStrength"][];
                };
            };
        };
    };
    v1_meta_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    v1_players_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
        };
    };
    v1_players_comps_retrieve: {
        parameters: {
            query?: {
                /** @description Number of comps, 1-50, default 10 */
                k?: number;
                /** @description Start year; default: the player's latest ranked season */
                season?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompsResponse"];
                };
            };
        };
    };
    v1_players_forecast_retrieve: {
        parameters: {
            query?: {
                /** @description Seasons ahead; only the fitted horizon (3) is available */
                horizon?: number;
                /** @description Start year; default: the player's latest ranked season */
                season?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    v1_players_outlook_retrieve: {
        parameters: {
            query?: {
                /** @description Start year; default: the player's latest season with 900+ minutes */
                season?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlookResponse"];
                };
            };
        };
    };
    v1_players_value_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerValue"];
                };
            };
        };
    };
    v1_players_search_list: {
        parameters: {
            query: {
                /** @description 1-25, default 10 */
                limit?: number;
                /** @description At least 2 characters */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSearchResult"][];
                };
            };
        };
    };
    v1_teams_profile_retrieve: {
        parameters: {
            query: {
                /** @description Start year; default: latest */
                season?: number;
                /** @description Exact team name (see /teams/search/) */
                team: string;
                /** @description Percentile at or below which a dimension is a gap, default 25 */
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfile"];
                };
            };
        };
    };
    v1_teams_search_list: {
        parameters: {
            query: {
                limit?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSearchResult"][];
                };
            };
        };
    };
    v1_teams_shortlist_retrieve: {
        parameters: {
            query: {
                /** @description A style dimension; default: the team's weakest */
                gap?: string;
                /** @description Default 29 */
                max_age?: number;
                /** @description Budget ceiling in EUR millions */
                max_value_m?: number;
                /** @description 1-25, default 8 */
                n?: number;
                season?: number;
                team: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortlistResponse"];
                };
            };
        };
    };
}
